// Generated by scripts/generate-build-info.mjs — do not edit.
export const APP_VERSION = "1.0.1";
export const APP_TAGLINE = "A bookmarks-driven, widget-extensible new tab page.";
export const GITHUB_REPO_URL = "https://github.com/tpbnick/new-tab-plus";
export const GITHUB_ISSUES_URL = "https://github.com/tpbnick/new-tab-plus/issues/new";
export const GITHUB_LICENSE_URL = "https://github.com/tpbnick/new-tab-plus/blob/main/LICENSE";
export const AUTHOR_NAME = 'Nick Platt';
export const AUTHOR_URL = 'https://nickplatt.dev';

export const LATEST_CHANGE = {
  shortSha: "afa0a9d",
  message: "Initial commit: New Tab Plus extension",
  date: "2026-06-26",
  commitUrl: "https://github.com/tpbnick/new-tab-plus/commit/afa0a9d63b663af3f41cca9cf713089e87dfde40",
} as const;
