// Generated by scripts/generate-build-info.mjs — do not edit.
export const APP_VERSION = "1.1.5";
export const APP_TAGLINE = "A bookmarks-driven, widget-extensible new tab page.";
export const GITHUB_REPO_URL = "https://github.com/tpbnick/new-tab-plus";
export const GITHUB_ISSUES_URL = "https://github.com/tpbnick/new-tab-plus/issues/new";
export const GITHUB_LICENSE_URL = "https://github.com/tpbnick/new-tab-plus/blob/main/LICENSE";
export const AUTHOR_NAME = 'Nick Platt';
export const AUTHOR_URL = 'https://nickplatt.dev';

export const LATEST_CHANGE = {
  shortSha: "5218320",
  date: "2026-06-28",
  commitUrl: "https://github.com/tpbnick/new-tab-plus/commit/52183206295d135a5f893ea19cb7a3bad5cbc157",
} as const;
